import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { createRequire } from 'node:module'

const __dirname = dirname(fileURLToPath(import.meta.url))
const svgPath = 'I:/deepseek-harness/apps/web/public/favicon.svg'
const sharpEntry = 'I:/deepseek-harness/node_modules/.pnpm/sharp@0.35.3_@types+node@22.20.0/node_modules/sharp/dist/index.cjs'

function loadSharp() {
  const req = createRequire(import.meta.url)
  for (const t of ['sharp', sharpEntry]) {
    try { return req(t) } catch { /* try next */ }
  }
  throw new Error('sharp not found; tried sharp / ' + sharpEntry)
}

const sharp = loadSharp()

if (!existsSync(svgPath)) {
  throw new Error('favicon.svg not found at ' + svgPath)
}

const src = readFileSync(svgPath, 'utf8')
// 提取鲸鱼路径（去掉样式与 fill，供自定义配色）
const whaleMatch = src.replace(/<style>[\s\S]*?<\/style>/, '').match(/<path id="path"[^/]*\/>/)
if (!whaleMatch) throw new Error('whale path not found')
// 去掉自带 fill（避免重复属性导致 XML 解析失败），并按用途分别填充
const whaleClean = whaleMatch[0].replace(/\sfill="[^"]*"/g, '').replace(/\sfill-opacity="[^"]*"/g, '')
const whaleBase = whaleClean.replace('<path id="path"', '<g transform="translate(3.5 3.5) scale(0.86)"><path')
const whaleWhite = whaleBase.replace('<path', '<path fill="#FFFFFF"')
const whaleBlack = whaleBase.replace('<path', '<path fill="#000000"')

// ---- 主图标（Windows 托盘）：苹果风 squircle + DeepSeek 蓝渐变 + 白色鲸鱼 + 顶部高光 ----
const bgGradient = '<defs>' +
  '<linearGradient id="bg" x1="0" y1="0" x2="0" y2="50" gradientUnits="userSpaceOnUse">' +
  '<stop offset="0" stop-color="#6E8BFF"/>' +
  '<stop offset="1" stop-color="#3A4FE0"/>' +
  '</linearGradient>' +
  '<radialGradient id="hl" cx="0.5" cy="0.05" r="1.1" gradientUnits="objectBoundingBox">' +
  '<stop offset="0" stop-color="#FFFFFF" stop-opacity="0.32"/>' +
  '<stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>' +
  '</radialGradient>' +
  '</defs>'
const squircle = '<rect x="0.5" y="0.5" width="49" height="49" rx="11.5" fill="url(#bg)"/>' +
  '<rect x="0.5" y="0.5" width="49" height="49" rx="11.5" fill="url(#hl)"/>'
// 鲸鱼缩小至 86% 并居中，留出苹果式呼吸边距（whaleWhite/whaleBlack 见上）
const mainSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 50 50">' + bgGradient + squircle + whaleWhite + '</g></svg>'

// ---- 模板图标（macOS 菜单栏）：纯黑鲸鱼、透明背景 ----
const templateSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 50 50">' + whaleBlack + '</g></svg>'

// 主 ICO 多尺寸（PNG 条目，Vista+）
const sizes = [16, 20, 24, 32, 40, 48, 64, 256]
const pngs = []
for (const s of sizes) {
  const data = await sharp(Buffer.from(mainSvg), { density: 384 }).resize(s, s).png().toBuffer()
  pngs.push({ size: s, data })
}

const header = Buffer.alloc(6)
header.writeUInt16LE(0, 0)
header.writeUInt16LE(1, 2)
header.writeUInt16LE(pngs.length, 4)

let offset = 6 + 16 * pngs.length
const entries = []
for (const { size, data } of pngs) {
  const e = Buffer.alloc(16)
  e[0] = size >= 256 ? 0 : size
  e[1] = size >= 256 ? 0 : size
  e[2] = 0
  e[3] = 0
  e.writeUInt16LE(1, 4)
  e.writeUInt16LE(32, 6)
  e.writeUInt32LE(data.length, 8)
  e.writeUInt32LE(offset, 12)
  entries.push(e)
  offset += data.length
}
const ico = Buffer.concat([header, ...entries, ...pngs.map((p) => p.data)])

// macOS 模板 PNG（44x44，Retina 菜单栏）
const template = await sharp(Buffer.from(templateSvg), { density: 384 }).resize(44, 44).png().toBuffer()

const b64 = (buf) => buf.toString('base64').match(/.{1,96}/g).join('\n')
const go =
  '// Code generated by scripts/gen-icon.mjs; DO NOT EDIT.\n' +
  'package main\n' +
  '\n' +
  'import "encoding/base64"\n' +
  '\n' +
  '// iconData 主图标（Windows 托盘）：苹果风蓝渐变 squircle + 白色鲸鱼（多尺寸 ICO）。\n' +
  'var iconData = mustDecodeIcon(iconDataB64)\n' +
  '\n' +
  '// iconDataTemplate macOS 菜单栏模板图标：纯黑鲸鱼、透明背景。\n' +
  'var iconDataTemplate = mustDecodeIcon(iconTemplateB64)\n' +
  '\n' +
  'const iconDataB64 = `' + b64(ico) + '`\n' +
  '\n' +
  'const iconTemplateB64 = `' + b64(template) + '`\n' +
  '\n' +
  'func mustDecodeIcon(b64 string) []byte {\n' +
  '    b, err := base64.StdEncoding.DecodeString(b64)\n' +
  '    if err != nil {\n' +
  '        panic("invalid embedded icon: " + err.Error())\n' +
  '    }\n' +
  '    return b\n' +
  '}\n'

const out = process.argv[2] ? resolve(process.argv[2]) : join(__dirname, '..', 'icon_gen.go')
writeFileSync(out, go)

// 预览图（便于肉眼检查）
const preview = await sharp(Buffer.from(mainSvg), { density: 384 }).resize(256, 256).png().toBuffer()
writeFileSync(join(dirname(out), 'preview.png'), preview)
const previewT = await sharp(Buffer.from(templateSvg), { density: 384 }).resize(128, 128).png().toBuffer()
writeFileSync(join(dirname(out), 'preview-template.png'), previewT)

console.log('wrote', out, '| ico bytes:', ico.length, '| template bytes:', template.length, '| go bytes:', go.length)
