import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { createRequire } from 'node:module'

const __dirname = dirname(fileURLToPath(import.meta.url))
const svgPath = 'I:/deepseek-harness/apps/web/public/favicon.svg'
const sharpEntry = 'I:/deepseek-harness/node_modules/.pnpm/sharp@0.35.3_@types+node@22.20.0/node_modules/sharp/dist/index.cjs'

function loadSharp() {
  const req = createRequire(import.meta.url)
  for (const t of ['sharp', sharpEntry]) {
    try { return req(t) } catch { /* try next */ }
  }
  throw new Error('sharp not found; tried sharp / ' + sharpEntry)
}

const sharp = loadSharp()

if (!existsSync(svgPath)) {
  throw new Error('favicon.svg not found at ' + svgPath)
}

let svg = readFileSync(svgPath, 'utf8')
// 去掉 dark-mode 的 <style>，强制鲸鱼为纯黑，并在其下铺白色圆角背景。
svg = svg.replace(/<style>[\s\S]*?<\/style>/, '')
svg = svg.replace(/\sfill="[^"]*"/g, '')
svg = svg.replace('<path id="path"', '<rect x="0" y="0" width="50" height="50" rx="11" fill="#ffffff"/><path id="path"')
svg = svg.replace('<path id="path"', '<path id="path" fill="#000000"')

const sizes = [16, 32]
const pngs = []
for (const s of sizes) {
  const data = await sharp(Buffer.from(svg), { density: 384 })
    .resize(s, s)
    .png()
    .toBuffer()
  pngs.push({ size: s, data })
}

// 组装多尺寸 ICO（Vista+ 支持 PNG 压缩条目）。
const header = Buffer.alloc(6)
header.writeUInt16LE(0, 0) // reserved
header.writeUInt16LE(1, 2) // type: icon
header.writeUInt16LE(pngs.length, 4) // count

let offset = 6 + 16 * pngs.length
const entries = []
for (const { size, data } of pngs) {
  const e = Buffer.alloc(16)
  e[0] = size >= 256 ? 0 : size
  e[1] = size >= 256 ? 0 : size
  e[2] = 0 // palette count
  e[3] = 0 // reserved
  e.writeUInt16LE(1, 4) // planes
  e.writeUInt16LE(32, 6) // bpp
  e.writeUInt32LE(data.length, 8) // bytes in resource
  e.writeUInt32LE(offset, 12) // offset
  entries.push(e)
  offset += data.length
}
const ico = Buffer.concat([header, ...entries, ...pngs.map((p) => p.data)])

const lines = ico.toString('base64').match(/.{1,96}/g)
const go =
  '// Code generated by scripts/gen-icon.mjs; DO NOT EDIT.\n' +
  'package main\n' +
  '\n' +
  'import "encoding/base64"\n' +
  '\n' +
  '// iconData 是白底黑鲸鱼托盘图标（多尺寸 ICO，PNG 压缩条目）。\n' +
  'var iconData = mustDecodeIcon()\n' +
  '\n' +
  'func mustDecodeIcon() []byte {\n' +
  '    const b64 = `' + lines.join('\n') + '`\n' +
  '    b, err := base64.StdEncoding.DecodeString(b64)\n' +
  '    if err != nil {\n' +
  '        panic("invalid embedded icon: " + err.Error())\n' +
  '    }\n' +
  '    return b\n' +
  '}\n'

const out = process.argv[2] ? resolve(process.argv[2]) : join(__dirname, '..', 'icon_gen.go')
writeFileSync(out, go)

// 预览图（便于肉眼检查）
const preview = await sharp(Buffer.from(svg), { density: 384 }).resize(256, 256).png().toBuffer()
writeFileSync(join(dirname(out), 'preview.png'), preview)

console.log('wrote', out, '| ico bytes:', ico.length, '| go bytes:', go.length)
